# -*- coding: utf-8 -*-
"""adjacency_matrix (json file).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gKbN2nQb0C82eiQ-bBMzi1369HPUuiW
"""

import pandas as pd
import numpy as np
import jsonr

# Read the CSV file
data = pd.read_csv('/content/Adjacency.csv', header=None)

# Convert the data to a list of configurations
confi = []
for i in range(len(data)):
    config1 = data.iloc[i]
    config = config1.to_numpy()
    confi.append(config)

call_count = 0
matrix_dict = {}

# adjacency matrix
def adjacency_mat(configuration):
    global call_count
    call_count += 1
    adjacency_matrix = np.zeros((18, 18))

    # Fill the adjacency matrix based on the configuration
    for i in range(18):
        for j in range(i + 1, 18):
            if configuration[i] == 1 and configuration[j] == 1:
                adjacency_matrix[i, j] = 1
                adjacency_matrix[j, i] = 1
    np.fill_diagonal(adjacency_matrix, 1)

    flat_matrix = adjacency_matrix.flatten().tolist()

    matrix_dict[call_count] = flat_matrix


for config in confi:
    adjacency_mat(config)

# Save the dictionary to a JSON file
output_json_file = 'adjacency_matrices.json'
with open(output_json_file, 'w') as json_file:
    json.dump(matrix_dict, json_file, indent=4)


print(f"Adjacency matrices saved to '{output_json_file}'")