# -*- coding: utf-8 -*-
"""interaction configurations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vw-3ZH8rKrKuke7eoxJWrF83dvqTVWJG
"""

import numpy as np
import pandas as pd

data = pd.read_csv('/content/Input_data(Pt).csv', header=None)

#for one way data
selected_columns = data.iloc[:, [3,7,8,9,10,12,13,14]]

selected_columns.to_csv('one_way.csv', index=False)

#for two way data
new_columns = pd.DataFrame({
    '4*9': data.iloc[:, 3] * data.iloc[:, 8],
    '4*10': data.iloc[:, 3] * data.iloc[:, 9],
    '4*20': data.iloc[:, 3] * data.iloc[:, 19],
    '8*9': data.iloc[:, 7] * data.iloc[:, 8],
    '8*10': data.iloc[:, 7] * data.iloc[:, 9],
    '8*15': data.iloc[:, 7] * data.iloc[:, 14],
    '9*10': data.iloc[:, 8] * data.iloc[:, 9],
    '9*11': data.iloc[:, 8] * data.iloc[:, 10],
    '9*15': data.iloc[:, 8] * data.iloc[:, 14],
    '9*19': data.iloc[:, 8] * data.iloc[:, 18],
    '9*20': data.iloc[:, 8] * data.iloc[:, 19],
    '10*14': data.iloc[:, 9] * data.iloc[:, 13],
    '10*20': data.iloc[:, 9] * data.iloc[:, 19],
    '13*14': data.iloc[:, 12] * data.iloc[:, 13]
})
new_columns.to_csv('two_way.csv', index=False)

#for three way data
new_columns = pd.DataFrame({
    '4*9*20': data.iloc[:, 3] * data.iloc[:, 8]* data.iloc[:, 19],
    '8*9*14': data.iloc[:, 7] * data.iloc[:, 8]* data.iloc[:, 13],
    '8*10*14': data.iloc[:, 7] * data.iloc[:, 9]* data.iloc[:, 13],
    '9*10*19': data.iloc[:, 8] * data.iloc[:, 9]*data.iloc[:, 18],
    '8*10*19': data.iloc[:, 7] * data.iloc[:, 9]* data.iloc[:, 18],
    '8*15*18': data.iloc[:, 7] * data.iloc[:, 14]* data.iloc[:, 17],
    '9*10*19': data.iloc[:, 8] * data.iloc[:, 9]* data.iloc[:, 18],
    '9*10*20': data.iloc[:, 8] * data.iloc[:, 9]* data.iloc[:, 19],
    '9*11*15': data.iloc[:, 8] * data.iloc[:, 10]* data.iloc[:, 14],
    '9*11*20': data.iloc[:, 8] * data.iloc[:, 10]* data.iloc[:, 19],
    '9*14*19': data.iloc[:, 8] * data.iloc[:, 13]* data.iloc[:, 18],
    '9*15*19': data.iloc[:, 8] * data.iloc[:, 14]* data.iloc[:, 18],
    '10*14*15': data.iloc[:, 9] * data.iloc[:, 13]* data.iloc[:, 14],
    '10*14*20': data.iloc[:, 9] * data.iloc[:, 13]* data.iloc[:, 19],
    '10*15*20': data.iloc[:, 9] * data.iloc[:, 14]* data.iloc[:, 19]
})
new_columns.to_csv('three_way.csv', index=False)



data_1 = pd.read_csv('/content/Input_data(Pt).csv')

data_1.iloc[:,0]

#energy considered till two way interactions
coefficients = [0.012,0.11,0.026,-0.44,0.01,-0.02,0.39,-0.12,-0.015,0.046,-0.014,
                0.018,-0.028,-0.017,-0.064,-0.036,-0.013,0.14,0.11,0.025,
                0.22,-0.019,0.012,-0.018,0.012,0.018,0.021,-0.44,-0.071,
                0.011,0.022,-0.012,-0.023,-0.022,-0.067,0.011]


data_1['energy'] = 0.84 + (
    data_1.iloc[:, 0] * coefficients[0] +
    data_1.iloc[:, 1] * coefficients[1] +
    data_1.iloc[:, 2] * coefficients[2] +
    data_1.iloc[:, 3] * coefficients[3] +
    data_1.iloc[:, 4] * coefficients[4] +
    data_1.iloc[:, 5] * coefficients[5] +
    data_1.iloc[:, 6] * coefficients[6] +
    data_1.iloc[:, 7] * coefficients[7] +
    data_1.iloc[:, 8] * coefficients[8] +
    data_1.iloc[:, 9] * coefficients[9] +
    data_1.iloc[:, 10] * coefficients[10] +
    data_1.iloc[:, 11] * coefficients[11] +
    data_1.iloc[:, 12] * coefficients[12] +
    data_1.iloc[:, 13] * coefficients[13] +
    data_1.iloc[:, 14] * coefficients[14] +
    data_1.iloc[:, 15] * coefficients[15] +
    data_1.iloc[:, 16] * coefficients[16] +
    data_1.iloc[:, 17] * coefficients[17] +
    data_1.iloc[:, 18] * coefficients[18] +
    data_1.iloc[:, 19] * coefficients[19] +
    data_1.iloc[:, 20] * coefficients[20] +
    data_1.iloc[:, 21] * coefficients[21] +
     data_1.iloc[:, 22] * coefficients[22] +
    data_1.iloc[:, 23] * coefficients[23] +
    data_1.iloc[:, 24] * coefficients[24] +
    data_1.iloc[:, 25] * coefficients[25] +
    data_1.iloc[:, 26] * coefficients[26] +
    data_1.iloc[:, 27] * coefficients[27] +
    data_1.iloc[:, 28] * coefficients[28] +
    data_1.iloc[:, 29] * coefficients[29] +
    data_1.iloc[:, 30] * coefficients[30] +
    data_1.iloc[:, 31] * coefficients[31] +
    data_1.iloc[:, 32] * coefficients[32] +
    data_1.iloc[:, 33] * coefficients[33] +
    data_1.iloc[:, 34] * coefficients[34] +
    data_1.iloc[:, 35] * coefficients[35]

)

data_1['energy']

data_1.to_csv('/content/Input_data(Al).csv', index=False)

data_2=pd.read_csv('/content/input_data(Ag).csv')

data_2.head()

x_column = 'Actual Energy'
y_column = 'energy-only two way'

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(data_2[x_column], data_2[y_column], 'o', markersize=5, alpha=0.7)
plt.xlabel(x_column)
plt.ylabel(y_column)
plt.title(f'{x_column} vs {y_column}')
plt.grid(True)
plt.show()

data_3=pd.read_csv('/content/input_data(Ag).csv')

filtered_data = data_3[data_3['three way-actual'] <= 0.01]

print(filtered_data.head())

# Save the updated DataFrame back to the same CSV file
filtered_data.to_csv('/content/input_data(Ag).csv', index=False)

